// Auto-generated by business-agent
const config = {
  name: "ProductPulse",
  tagline: "Unlock Profitable Digital Product Ideas",
  description: "ProductPulse helps entrepreneurs find profitable digital product ideas by analyzing market trends. Get ahead of the competition with our simple SaaS tool.",
  primaryColor: "emerald",
  accentColor: "green",
  features: ["Market trend analysis","Profitable digital product idea suggestions","Product idea filtering"],
  niche: "digital-downloads",
  targetAudience: "Entrepreneurs, product creators",
  monetization: ["Primary: Subscription-based model ($29/month)","Secondary: Affiliate marketing for digital product creators"],
  seoStrategy: {"keywords":["digital product research","profitable digital products","market trend analysis"],"contentStrategy":"Create high-quality, informative blog posts and guides for digital product creators"},
};

export default config;
